/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50505
Source Host           : 127.0.0.1:3306
Source Database       : epan

Target Server Type    : MYSQL
Target Server Version : 50505
File Encoding         : 65001

Date: 2017-04-21 19:08:51
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `xepan_cms_image_gallery_categories`
-- ----------------------------
DROP TABLE IF EXISTS `xepan_cms_image_gallery_categories`;
CREATE TABLE `xepan_cms_image_gallery_categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `status` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `created_by_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;

-- ----------------------------
-- Records of xepan_cms_image_gallery_categories
-- ----------------------------
INSERT INTO `xepan_cms_image_gallery_categories` VALUES ('3', 'Test', 'Active', 'ImageGalleryCategory', '2017-04-20 16:18:29', '90');

-- ----------------------------
-- Table structure for `xepan_cms_image_gallery_images`
-- ----------------------------
DROP TABLE IF EXISTS `xepan_cms_image_gallery_images`;
CREATE TABLE `xepan_cms_image_gallery_images` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `description` longtext,
  `gallery_cat_id` int(11) DEFAULT NULL,
  `image_id` int(11) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `created_by_id` int(11) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4;

-- ----------------------------
-- Records of xepan_cms_image_gallery_images
-- ----------------------------
INSERT INTO `xepan_cms_image_gallery_images` VALUES ('6', 'Happy Diwali 3', 'LOREM IPSUE IS SIMPLY DUMMY HEADER LOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINES', '3', '18', 'Active', '90', 'ImageGallery', '2017-04-20 16:21:22');
INSERT INTO `xepan_cms_image_gallery_images` VALUES ('7', 'SEr Superior', 'LOREM IPSUE IS SIMPLY DUMMY HEADER LOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINES', '3', '21', 'Active', '90', 'ImageGallery', '2017-04-20 16:21:40');
INSERT INTO `xepan_cms_image_gallery_images` VALUES ('8', 'test', 'LOREM IPSUE IS SIMPLY DUMMY HEADER LOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINES', '3', '24', 'Active', '90', 'ImageGallery', '2017-04-20 16:21:54');
INSERT INTO `xepan_cms_image_gallery_images` VALUES ('9', 'Heart', 'LOREM IPSUE IS SIMPLY DUMMY HEADER LOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINESLOREM IPSUE IS SIMPLY DUMMY HEADER IN MULTIPLE LINES', '3', '27', 'Active', '90', 'ImageGallery', '2017-04-20 16:22:05');